name: haskell-ray-tracer
version: 0.1.0.0
description: |
  Please see the README on GitHub
  at <https://github.com/godu/haskell-ray-tracer#readme>
author: Arthur Weber
maintainer: arthur.weber@viacesi.fr
license: BSD3
github: godu/haskell-ray-tracer
extra-source-files:
  - README.md
dependencies:
  - base >= 4.7 && < 5
ghc-options:
  - -W
  - -Werror
library:
  source-dirs: src
  dependencies:
    - containers
    - foldl
    - semirings
    - vector
executables:
  haskell-ray-tracer-exec:
    main: RayTracer/Main.hs
    source-dirs: app
    dependencies:
      - haskell-ray-tracer
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -fexcess-precision
      - -optc-O3
      - -optc-ffast-math
      - -funfolding-use-threshold=16
tests:
  haskell-ray-tracer-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - haskell-ray-tracer
      - hspec
