name: haskell-ray-tracer
version: 0.1.0.0
github: godu/haskell-ray-tracer
license: BSD3
author: Arthur Weber
maintainer: arthur.weber@viacesi.fr
copyright: "2021 Arthur Weber"

extra-source-files:
  - README.md

description: "The Ray Tracer Challenge: A Test-Driven Guide to Your First 3D Renderer"

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Werror
  - -Wno-name-shadowing
  - -Wno-type-defaults

library:
  source-dirs: src
  dependencies:
    - containers
    - foldl
    - semirings
    - vector

executables:
  haskell-ray-tracer-exec:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-ray-tracer
tests:
  haskell-ray-tracer-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - haskell-ray-tracer
      - hspec

default-extensions:
  - Strict
  - StrictData
  - FlexibleInstances
  - TupleSections
  - MultiParamTypeClasses
